import { execFileSync, execSync } from 'node:child_process';
import { writeFileSync, unlinkSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { MigrationPlan } from './types.js';

export type PrResult = {
  branch: string;
  prUrl?: string;
  message: string;
};

function sh(cmd: string, cwd: string): string {
  return execSync(cmd, { cwd, encoding: 'utf8' }).trim();
}

function hasGh(): boolean {
  try {
    execSync('gh --version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Create a branch, commit migration files, push, and open a PR via gh.
 * Requires a clean-enough git state and gh auth.
 */
export function createMigrationPr(
  repoRoot: string,
  plan: MigrationPlan,
  files: string[],
): PrResult {
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const branch = `maintain/${plan.provider}-${stamp}-${Date.now().toString(36).slice(-4)}`;

  const current = sh('git rev-parse --abbrev-ref HEAD', repoRoot);
  sh(`git checkout -b ${branch}`, repoRoot);

  try {
    if (files.length) {
      execFileSync('git', ['add', ...files], { cwd: repoRoot });
    }
    const status = sh('git status --porcelain', repoRoot);
    if (!status) {
      sh(`git checkout ${current}`, repoRoot);
      sh(`git branch -D ${branch}`, repoRoot);
      return {
        branch,
        message: 'No file changes to commit — PR not created.',
      };
    }

    const commitMsg = `${plan.title}\n\nGenerated by astro-maintain.\nRisk: ${plan.risk}`;
    execFileSync('git', ['commit', '-m', commitMsg], { cwd: repoRoot });

    if (!hasGh()) {
      return {
        branch,
        message: `Committed on ${branch}. Install/auth gh to open a PR, or push manually.`,
      };
    }

    sh(`git push -u origin HEAD`, repoRoot);

    const body = [
      plan.explanation,
      '',
      '## Risk notes',
      ...plan.riskNotes.map((n) => `- ${n}`),
      '',
      '## Test plan',
      ...plan.testPlan.map((t) => `- [ ] ${t}`),
      '',
      '---',
      '_PR opened by `astro-maintain`_',
    ].join('\n');

    const tmp = path.join(os.tmpdir(), `astro-maintain-pr-${Date.now()}.md`);
    writeFileSync(tmp, body, 'utf8');
    try {
      const url = sh(
        `gh pr create --title ${shellQuote(plan.title)} --body-file ${shellQuote(tmp)}`,
        repoRoot,
      );
      return { branch, prUrl: url.split('\n').pop()?.trim(), message: 'PR created.' };
    } finally {
      try {
        unlinkSync(tmp);
      } catch {
        // ignore
      }
    }
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    return { branch, message: `PR flow failed: ${msg}` };
  }
}

function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}
